apiVersion: v1
kind: Service
metadata:
  name: mssql-nodeport-svc
spec:
  selector:
    app: mssql-server-app
  ports:
    - protocol: "TCP"
      port: 1433 # The port that the service is running on in the cluster
      targetPort: 1433 # The port exposed by the service
  type: NodePort # type of the service.