kind: PersistentVolume
apiVersion: v1
metadata:
  name: mssql-pv
  labels:
    app: mssql-server-app
spec:
  accessModes:
    - "ReadWriteOnce"
  capacity:
    storage: 8Gi
  hostPath:
    path: /c/mssql-volume/data-backup