kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssql-pvc
  labels:
    app: mssql-server-app
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi