apiVersion: v1
kind: Service
metadata:
  name: mssql-deployment
  labels:
    app: mssql-server-app
spec:
  selector:
    app: mssql-server-app
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: LoadBalancer